[Settings]
ID = "f5f37764-deec-4e75-8641-958675a9f00f"

# Settings in the [build] context are 
[build]
  publish = "build"
  command = "npm run build"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200